### ISSUE TITLE
Random flag error

### ISSUE THREAD

**Issue by coder26-cmd** [VFDan/Flag-Guesser#4]
The following exception occurred during the execution:

<pre>index.js:2 Uncaught TypeError: Cannot read property 'name' of undefined
    at randomFlag (index.js:2)
    at newFlag (index.js:5)
    at HTMLButtonElement.onclick (index.html:11)
randomFlag @ index.js:2
newFlag @ index.js:5
onclick @ index.html:11</pre>

The randomizer seems to work fine, I can't catch this bug. Could you, please, fix that?

**Comment by VFDan** [comment]
What flag does this appear on?

**Comment by coder26-cmd** [comment]
When this error appears, the flag image doesn't change.

**Comment by coder26-cmd** [comment]
Oh, I see now. `countries[40]` returns `undefined`. Yeah, that because of the extra comma after `countries[39]`

**Comment by VFDan** [comment]
Oh ok. I'll just fix that then.
